### ISSUE TITLE
[Bug] Unable to parse input file, are you sure the Vyper code is valid?

### ISSUE THREAD

**Issue by PatrickAlphaC** [benber86/mamushi#43]
**Describe the bug**
I'm running the formatter and getting:

```
Unable to parse input file, are you sure the Vyper code is valid?
```

**To Reproduce**

Add `snekmate` into your python virtual environment, then make a file as such:

```python
from snekmate.auth import ownable
initializes: ownable

exports: (
    ownable.__interface__
)

@deploy
def __init__():
    ownable.__init__()
```

Then, try to format it:

```
mamushi .
```

You'll get the error

**Expected behavior**
You should not get the error

**Desktop (please complete the following information):**
 - OS: MacOS 15.0.1 
 - Mamushi version 0.0.3
 - Vyper version: 0.4.0

**Comment by benber86** [comment]
Should be fixed in 0.0.4
